language: rust
rust:
  - stable
  - 1.32.0 # minimum supported version
  - 1.34.0 # development version
  - 1.37.0 # latest version
  - nightly
cache: cargo
# TODO: Upload to Github Releases
# see: https://docs.travis-ci.com/user/deployment/releases
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true